#! /bin/bash
#
#  Copyright (c) 2006-2011, Karl Trygve Kalleberg <karltk near strategoxt dot org>
#
#  Licensed under the GNU Lesser General Public License, v2.1

jars="
jjtraveler-0.4.3.jar
junit-3.8.2.jar
org.eclipse.core.contenttype_3.3.0.v20080604-1400.jar
org.eclipse.core.jobs_3.4.0.v20080512.jar
org.eclipse.core.resources_3.4.0.v20080604-1400.jar
org.eclipse.core.runtime_3.4.0.v20080512.jar
org.eclipse.equinox.common_3.4.0.v20080421-2006.jar
org.eclipse.equinox.preferences_3.2.200.v20080421-2006.jar
org.eclipse.equinox.registry_3.4.0.v20080516-0950.jar
org.eclipse.jdt.core_3.4.0.v_874.jar
org.eclipse.jface.text_3.4.0.v20080603-2000.jar
org.eclipse.osgi_3.4.0.v20080605-1900.jar
org.eclipse.text_3.4.0.v20080605-1800.jar
shared-objects-1.4.jar
spoofax-aterm-0.2.0.jar
spoofax-aterm-adapter-0.1.1.jar
spoofax-interpreter-core-0.3.12.jar
spoofax-ecj-adapter-0.1.3.jar
"

bp=$(dirname $0)
jp=${bp}/../share/java

absjars=""
for x in ${jars} ; do
	absjars="${absjars}:${jp}/$x"
done

#echo ${absjars}
java -cp ${absjars} \
	org.spoofax.ecjadapter.ParseJava \
	$@
