#! /bin/bash
#
#  Copyright (c) 2006-2007, Karl Trygve Kalleberg <karltk@ii.uib.no>
#
#  Licensed under the GNU General Public License, v2

eclipse_plugins="
    org.eclipse.core.runtime
    org.eclipse.equinox.common
    org.eclipse.core.jobs
    org.eclipse.core.contenttype
    org.eclipse.equinox.registry
    org.eclipse.equinox.preferences
    org.eclipse.jdt.core
    org.eclipse.osgi
    org.eclipse.core.resources"

function latest() {
	ls ${ep}/${1}_*.jar | \
		sort | \
		tail -n 1
}

function compute-eclipse-plugins() {
	local e=""
	for x in ${eclipse_plugins} ; do
		e="${e}:$(latest $x)"
	done
	echo $e
}

ep=${ECLIPSE_HOME:-${HOME}/apps/eclipse/plugins}
bp=$(dirname $0)
eclipsejars="$(compute-eclipse-plugins)"

java -cp \
	${bp}/bin:${bp}/../org.spoofax.aterm/bin:${bp}/../org.spoofax.interpreter.adapter.aterm/bin:${bp}/../org.spoofax.interpreter/bin:${bp}/../org.spoofax.aterm/lib/shared-objects-1.4.jar:${bp}/../org.spoofax.aterm/lib/jjtraveler-0.4.3.jar:${eclipsejars} \
	org.spoofax.ecjadapter.ParseJava \
	$@

