#! /bin/bash

function dbg() {
	echo $* > /dev/stderr
}

function die() {
	echo $* > /dev/stderr
	exit 1
}

function usage() {
	echo "[xlet       ] $(basename $0) -x <action> <project-path> <file>"
	echo "[interpreter] $(basename $0) -i <file>.ctree"
}

function run-xlet() {
	invoke-interpreter org.spoofax.xlet.Main $@
}

function run-interpreter() {
	dbg "xx" $@
	invoke-interpreter "$@"

}

function invoke-interpreter() {
	dbg -cp ${bp}/../org.spoofax.aterm/bin:${bp}/bin:${bp}/../org.spoofax.aterm/lib/jjtraveler-0.4.3.jar:${bp}/../org.spoofax.aterm/lib/shared-objects-1.4.jar:${bp}/../org.spoofax.interpreter.adapters/bin
	dbg "args " $@

	java ${VM_OPTS} \
		-cp ${bp}/../org.spoofax.aterm/bin:${bp}/bin:${bp}/../org.spoofax.aterm/lib/jjtraveler-0.4.3.jar:${bp}/../org.spoofax.aterm/lib/shared-objects-1.4.jar:${bp}/../org.spoofax.interpreter.adapters/bin:${libpath} \
		-Dspoofax.lib.path=../xlet/src \
		-Dspoofax.xlet.path=../org.spoofax.interpreter/bin/xlets \
		${javadefs} \
		org.spoofax.interpreter.core.Main \
		${lib} \
		${factory} \
		$@
}

function verify-project() {
	if [ ! -f $1/.project ] ; then
		die "$1 does not contain a project"
	fi
	echo "[ Using project $(abspath $1) ]" 
}

function verify-action() {
	if [ ! -f org.spoofax.interpreter/bin/xlets/$1.xlet ] ; then
		die "$1 is not a known action"
	fi
	echo "[ Using xlet $(abspath $1) ]"
}

function abspath() {
	pushd . > /dev/null
	cd $(dirname $1)
	echo $(pwd)/$(basename $1)
	popd > /dev/null
}


flags=""
file=""
action=""

bp=$(dirname $0)
while [ $# -gt 0 ] ; do
	dbg $1
	case $1 in
		-x|--xlet)
			action="xlet"
			;;
		-i|--interpret)
			action="itp"
			;;
		-f|--factory)
			shift
			factory="-f $1"
			;;
		-l|--library)
			shift
			if [ "${lib}" == "" ] ; then
				lib="-l $1"
			else
				lib="${lib},$1"
			fi
			;;
		-L|--libpath)
			shift
			libpath="${libpath}:$1"
			;;
		-D)
			shift
			javadefs="${javadefs} -D$1"
			;;
		-d|--debug) 
			flags="${flags} --debug"
			;;
		--)
			break
			;;
		-*)
			usage
			exit 1
			;;
		*)
			file="${file} $1"
			;;
	esac
	shift
done

if [ "${action}" == "xlet" ] ; then
	verify-action $2
	verify-project $3
	run-xlet $2 $3 $4
elif [ "${action}" == "itp" ] ; then
	run-interpreter ${flags} -i ${file} "$@"
else
	usage
fi


