#!/bin/bash

interp_jar=../org.spoofax.interpreter/bin
jsglr_jar=../org.spoofax.jsglr/bin
jsglrlib_jar=../org.spoofax.interpreter.library.jsglr/bin
atermadapter_jar=../org.spoofax.interpreter.adapter.aterm/bin
aterm_jar=../org.spoofax.aterm/bin:../org.spoofax.aterm/lib/jjtraveler-0.4.3.jar:../org.spoofax.aterm/lib/shared-objects-1.4.jar

echo ${STRATEGO_HOME}
stratego_dir=${STRATEGO_HOME:-$HOME/.nix-profile}
echo ${stratego_dir}

java -Dstratego.dir=${stratego_dir} \
	-cp bin:${interp_jar}:${jsglr_jar}:${atermadapter_jar}:${aterm_jar}:${jsglrlib_jar} \
	org.spoofax.compiler.Main \
	$*
