#! /bin/sh
#
# Further reading unconditionally incurs a 4D10 sanity loss.
#


rm -f /tmp/foo-test-test*

echo $1 $2 "|$3|"
(
	echo "module foo-test-test"
	echo "imports liblib"
	echo "strategies"
	echo "main = "
) > /tmp/foo-test-test.str

sed \
	-e 's/;;/;/g' \
	-e 's/; *$//' \
	< $1 >> /tmp/foo-test-test.str

~/.nix-profile/bin/strc --keep 10 -i /tmp/foo-test-test.str


tafname="$(echo $3 | sed 's/ /_/g')"

pp-aterm -i /tmp/foo-test-test.sci.opt17 > data/${tafname}.rtree

